import Head from "next/head";
import { FC, useState } from "react";
import { mediaUrl } from "../utils/mediaUrl";

const Home: FC = () => {
  const [selectedImage, setSelectedImage] = useState(null);
  const [uploadedImage, setUploadedImage] = useState(null);
  const [showRemoveBtn, setShowRemoveBtn] = useState(false);

  const inputChangeHandel = (e: any) => {
    if (e) {
      const conventMedia = mediaUrl(e);
      conventMedia && setSelectedImage(conventMedia);
    }
  };

  const uploadHandel = () => {};

  const removeHandel = () => {};

  const uplodImageHoveHandel = () => {
    setShowRemoveBtn(!showRemoveBtn);
  };

  return (
    <>
      <Head>
        <title>Create Next App </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="next-main">
        <div className="next-sec">
          <div className="top-sec">
            <div className="select-media-sec">
              <label htmlFor="next-input" className="select-label">
                {selectedImage ? (
                  <img
                    className="select-img img"
                    src={`${selectedImage}`}
                    alt={`${selectedImage}`}
                  />
                ) : (
                  <h1 className="select-img-text">
                    <span>Select image</span>
                  </h1>
                )}
              </label>
              <input
                type="file"
                id="next-input"
                hidden
                onChange={inputChangeHandel}
              />
            </div>
            <div className="upload-btn-sec">
              <button className="upload-btn" onClick={uploadHandel}>
                Upload
              </button>
            </div>
          </div>
          {uploadedImage && (
            <div className="bottom-sec">
              <div className="upload-heading-sec">
                <h1 className="upload-heading">
                  <span>Uploaded image</span>
                </h1>
              </div>
              <div
                className="upload-img-sec"
                onMouseEnter={uplodImageHoveHandel}
                onMouseLeave={uplodImageHoveHandel}
              >
                <img
                  className="upload-img img"
                  src={`${setUploadedImage}`}
                  alt={`${setUploadedImage}`}
                />
                {showRemoveBtn && (
                  <div className="remove-btn" onClick={removeHandel}>
                    <h2 className="remove-btn-text">
                      <span>REMOVE</span>
                    </h2>
                  </div>
                )}
              </div>
            </div>
          )}
        </div>
      </main>
    </>
  );
};

export default Home;
